#!/bin/bash
cd src 
nm=$1
if [ ${#nm} -lt 1 ] ; then 
 echo usage: 
 echo $0 name_of_paper
 exit
fi 
nm=` echo $nm | cut -d '.' -f 1 `
nm=` echo $nm | cut -d '/' -f 2 `
echo $nm
#
cd src
for x in 1  ; do 
  pdflatex $nm
#  xelatex src/$nm
  bibtex $nm
done
mycount=`detex ${nm}.tex  | wc`
echo "wordcount " $mycount
mv $nm.pdf ../
rm ${nm}.out ${nm}.aux ${nm}.bbl ${nm}.log ${nm}.blg
cd ..
